import 'package:watch_hub_frontend/models/watch.dart';
import 'package:watch_hub_frontend/models/review.dart';

class DummyData {
  DummyData._();

  // Helper list of Unsplash URLs for watch styles to keep URL pool rich and premium
  static const List<String> _luxuryUrls = [
    'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=600&auto=format&fit=crop&q=80', // Gold Rolex-like
    'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&auto=format&fit=crop&q=80', // Black dial black leather
    'https://images.unsplash.com/photo-1619134778706-7015533a6150?w=600&auto=format&fit=crop&q=80', // Steel watch blue dial
    'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&auto=format&fit=crop&q=80', // Minimal luxury
  ];

  static const List<String> _classicUrls = [
    'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&auto=format&fit=crop&q=80', // Classic rose gold
    'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&q=80', // Classic white face
    'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=600&auto=format&fit=crop&q=80', // Leather watch
    'https://images.unsplash.com/photo-1517502884422-41eaaced0168?w=600&auto=format&fit=crop&q=80', // Mechanical desk watch
  ];

  static const List<String> _sportUrls = [
    'https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=600&auto=format&fit=crop&q=80', // Blue diver sport watch
    'https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600&auto=format&fit=crop&q=80', // Sport digital watch
    'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&auto=format&fit=crop&q=80', // Bold chronometer
    'https://images.unsplash.com/photo-1600857062241-98e5dba7f214?w=600&auto=format&fit=crop&q=80', // Modern sport strap
  ];

  static const List<String> _smartUrls = [
    'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=600&auto=format&fit=crop&q=80', // Apple Watch fitness style
    'https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=600&auto=format&fit=crop&q=80', // Dark smartwatch
    'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop&q=80', // Active screen smartwatch
    'https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?w=600&auto=format&fit=crop&q=80', // Casual smartwatch face
  ];

  static final List<Review> _reviews = [
    Review(id: 'r1', userName: 'John Doe', rating: 5.0, comment: 'Absolutely brilliant craftsmanship. Exceeded all expectations!', date: DateTime.now().subtract(const Duration(days: 3))),
    Review(id: 'r2', userName: 'Sarah Jenkins', rating: 4.5, comment: 'Gorgeous look, fits perfectly on my wrist. The dial color is striking.', date: DateTime.now().subtract(const Duration(days: 12))),
    Review(id: 'r3', userName: 'Alex Rivera', rating: 4.0, comment: 'Solid build quality. Keeps accurate time. Highly recommended.', date: DateTime.now().subtract(const Duration(days: 20))),
  ];

  static final List<Watch> watches = [
    // --- ROLEX (4) ---
    Watch(
      id: 'rolex-1',
      brand: 'Rolex',
      model: 'Submariner Date',
      category: 'Luxury',
      price: 10500.00,
      discount: 0.05,
      description: 'The archetype of the diver\'s watch, the Rolex Submariner Date exemplifies the historic link between Rolex and deep-sea exploration.',
      specifications: {
        'Movement': 'Automatic Calibre 3235',
        'Case Material': 'Oystersteel',
        'Case Size': '41mm',
        'Glass': 'Scratch-resistant sapphire',
        'Water Resistance': '300m (1,000 feet)',
        'Power Reserve': '70 Hours',
        'Strap': 'Oyster steel bracelet',
      },
      images: [_luxuryUrls[2], _luxuryUrls[1]],
      rating: 4.9,
      reviews: _reviews,
      stock: 5,
      colors: ['Silver', 'Black', 'Green'],
      sizes: ['41mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'rolex-2',
      brand: 'Rolex',
      model: 'Daytona Cosmograph',
      category: 'Luxury',
      price: 14800.00,
      discount: 0.0,
      description: 'Designed to meet the demands of professional racing drivers, the Cosmograph Daytona is an icon joined at the join to high performance.',
      specifications: {
        'Movement': 'Automatic Calibre 4130',
        'Case Material': '18ct Yellow Gold',
        'Case Size': '40mm',
        'Glass': 'Scratch-resistant sapphire',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '72 Hours',
        'Strap': 'Oysterflex rubber strap',
      },
      images: [_luxuryUrls[0], _luxuryUrls[1]],
      rating: 4.8,
      reviews: _reviews,
      stock: 3,
      colors: ['Gold', 'Black dial'],
      sizes: ['40mm'],
      isFeatured: true,
      isPopular: false,
      isNewArrival: true,
      isRecommended: false,
    ),
    Watch(
      id: 'rolex-3',
      brand: 'Rolex',
      model: 'Datejust 41',
      category: 'Luxury',
      price: 9200.00,
      discount: 0.0,
      description: 'The Rolex Datejust is the modern archetype of the classic watch, thanks to aesthetics and functions that transcend changes in fashion.',
      specifications: {
        'Movement': 'Automatic Calibre 3235',
        'Case Material': 'Oystersteel and White Gold',
        'Case Size': '41mm',
        'Glass': 'Sapphire with Cyclops lens',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '70 Hours',
        'Strap': 'Jubilee steel bracelet',
      },
      images: [_classicUrls[0], _classicUrls[1]],
      rating: 4.7,
      reviews: _reviews,
      stock: 8,
      colors: ['Blue Dial', 'Silver Dial', 'Dark Grey'],
      sizes: ['36mm', '41mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'rolex-4',
      brand: 'Rolex',
      model: 'Oyster Perpetual',
      category: 'Luxury',
      price: 6400.00,
      discount: 0.0,
      description: 'The Oyster Perpetual model expresses the essence of the Oyster concept, providing a clear and accurate time display.',
      specifications: {
        'Movement': 'Automatic Calibre 3230',
        'Case Material': 'Oystersteel',
        'Case Size': '36mm',
        'Glass': 'Scratch-resistant sapphire',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '70 Hours',
        'Strap': 'Oyster steel bracelet',
      },
      images: [_classicUrls[2], _classicUrls[3]],
      rating: 4.6,
      reviews: _reviews,
      stock: 12,
      colors: ['Silver', 'Green Dial', 'Tiffany Blue'],
      sizes: ['31mm', '36mm', '41mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: true,
    ),

    // --- OMEGA (4) ---
    Watch(
      id: 'omega-1',
      brand: 'Omega',
      model: 'Speedmaster Moonwatch Professional',
      category: 'Luxury',
      price: 7600.00,
      discount: 0.10,
      description: 'The Speedmaster Moonwatch is one of the world’s most iconic timepieces, having been a part of all six moon landings.',
      specifications: {
        'Movement': 'Manual-winding Omega Calibre 3861',
        'Case Material': 'Stainless Steel',
        'Case Size': '42mm',
        'Glass': 'Hesalite or Sapphire crystal',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': '50 Hours',
        'Strap': 'Stainless steel bracelet',
      },
      images: [_luxuryUrls[1], _luxuryUrls[3]],
      rating: 4.9,
      reviews: _reviews,
      stock: 6,
      colors: ['Black Dial', 'Silver Dial'],
      sizes: ['42mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'omega-2',
      brand: 'Omega',
      model: 'Seamaster Diver 300M',
      category: 'Sport',
      price: 5900.00,
      discount: 0.08,
      description: 'Since 1993, the Seamaster Professional Diver 300M has enjoyed a legendary following. Today’s collection embraces that ocean heritage.',
      specifications: {
        'Movement': 'Automatic Omega Calibre 8800',
        'Case Material': 'Stainless Steel',
        'Case Size': '42mm',
        'Glass': 'Sapphire crystal with anti-reflective treatment',
        'Water Resistance': '300m (1,000 feet)',
        'Power Reserve': '55 Hours',
        'Strap': 'Blue rubber strap or steel bracelet',
      },
      images: [_sportUrls[0], _sportUrls[2]],
      rating: 4.8,
      reviews: _reviews,
      stock: 10,
      colors: ['Blue Dial', 'Black Dial', 'White Dial'],
      sizes: ['42mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'omega-3',
      brand: 'Omega',
      model: 'Constellation Co-Axial',
      category: 'Classic',
      price: 8900.00,
      discount: 0.0,
      description: 'The dramatic and enduring design of the OMEGA Constellation is characterised by its famous half-moons, "claws" on the case.',
      specifications: {
        'Movement': 'Automatic Omega Calibre 8900',
        'Case Material': '18K Sedna Gold and Stainless Steel',
        'Case Size': '39mm',
        'Glass': 'Sapphire with anti-reflective coating',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': '60 Hours',
        'Strap': 'Leather strap with gold foldover clasp',
      },
      images: [_luxuryUrls[3], _luxuryUrls[0]],
      rating: 4.6,
      reviews: _reviews,
      stock: 4,
      colors: ['Sedna Gold', 'Stainless Steel'],
      sizes: ['39mm'],
      isFeatured: true,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),
    Watch(
      id: 'omega-4',
      brand: 'Omega',
      model: 'Aqua Terra 150M',
      category: 'Classic',
      price: 6100.00,
      discount: 0.0,
      description: 'The Seamaster Aqua Terra is a superb tribute to OMEGA’s rich maritime heritage, with a teak concept dial representing luxury yacht decks.',
      specifications: {
        'Movement': 'Automatic Omega Calibre 8900',
        'Case Material': 'Stainless Steel',
        'Case Size': '41mm',
        'Glass': 'Dome scratch-resistant sapphire',
        'Water Resistance': '150m (500 feet)',
        'Power Reserve': '60 Hours',
        'Strap': 'Integrated green rubber strap',
      },
      images: [_classicUrls[2], _classicUrls[0]],
      rating: 4.7,
      reviews: _reviews,
      stock: 7,
      colors: ['Green Dial', 'Teak Blue', 'Silver'],
      sizes: ['38mm', '41mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: true,
      isRecommended: true,
    ),

    // --- CASIO (4) ---
    Watch(
      id: 'casio-1',
      brand: 'Casio',
      model: 'G-Shock Mudmaster',
      category: 'Sport',
      price: 350.00,
      discount: 0.15,
      description: 'Designed for extreme conditions on land, the Mudmaster is sealed to prevent entry of mud, sand, and dust, featuring Triple Sensor.',
      specifications: {
        'Movement': 'Quartz Tough Solar',
        'Case Material': 'Resin / Stainless steel bezel',
        'Case Size': '54.4mm',
        'Glass': 'Mineral glass or Sapphire',
        'Water Resistance': '200m (660 feet)',
        'Power Reserve': 'Solar powered (approx. 7 months rechargeable)',
        'Strap': 'Heavy duty resin band',
      },
      images: [_sportUrls[1], _sportUrls[3]],
      rating: 4.7,
      reviews: _reviews,
      stock: 25,
      colors: ['Black', 'Tactical Green', 'Desert Tan'],
      sizes: ['Standard (Large)'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: false,
    ),
    Watch(
      id: 'casio-2',
      brand: 'Casio',
      model: 'Vintage Digital A168WA',
      category: 'Classic',
      price: 49.99,
      discount: 0.0,
      description: 'Retro classic style that never fades. An elegant, retro-futuristic digital metal watch with electro-luminescent backlight.',
      specifications: {
        'Movement': 'Quartz Digital',
        'Case Material': 'Resin / Chrome plated',
        'Case Size': '38.6mm',
        'Glass': 'Resin glass',
        'Water Resistance': 'Water Resistant (30m)',
        'Power Reserve': 'CR2016 Battery (approx. 7 years)',
        'Strap': 'Stainless steel self-adjustable band',
      },
      images: [_classicUrls[1], _classicUrls[3]],
      rating: 4.8,
      reviews: _reviews,
      stock: 50,
      colors: ['Silver', 'Gold', 'Gunmetal'],
      sizes: ['38.6mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'casio-3',
      brand: 'Casio',
      model: 'G-Shock GA-2100 "CasiOak"',
      category: 'Sport',
      price: 120.00,
      discount: 0.0,
      description: 'The ultra-thin carbon core guard structure analog-digital watch has captured the watch world with its octagonal bezel.',
      specifications: {
        'Movement': 'Quartz Analog-Digital',
        'Case Material': 'Carbon / Resin',
        'Case Size': '45.4mm',
        'Glass': 'Mineral glass',
        'Water Resistance': '200m (660 feet)',
        'Power Reserve': 'SR726W Battery (approx. 3 years)',
        'Strap': 'Resin band',
      },
      images: [_sportUrls[3], _sportUrls[1]],
      rating: 4.9,
      reviews: _reviews,
      stock: 30,
      colors: ['Stealth Black', 'Red', 'Grey', 'Navy Blue'],
      sizes: ['45.4mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'casio-4',
      brand: 'Casio',
      model: 'Edifice Chronograph EFR-556',
      category: 'Sport',
      price: 180.00,
      discount: 0.10,
      description: 'Elegant chronograph designed for motorsport enthusiasts, featuring carbon fiber look accents and multi-dial stopwatch functions.',
      specifications: {
        'Movement': 'Quartz Chronograph',
        'Case Material': 'Stainless steel',
        'Case Size': '48.7mm',
        'Glass': 'Mineral glass',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': 'SR920SW Battery (approx. 3 years)',
        'Strap': 'Genuine leather or steel bracelet',
      },
      images: [_sportUrls[2], _classicUrls[2]],
      rating: 4.5,
      reviews: _reviews,
      stock: 15,
      colors: ['Silver-Black', 'Blue-Gold'],
      sizes: ['48.7mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- SEIKO (4) ---
    Watch(
      id: 'seiko-1',
      brand: 'Seiko',
      model: 'Seiko 5 Sports Automatic',
      category: 'Sport',
      price: 295.00,
      discount: 0.12,
      description: 'For over 50 years, Seiko 5 Sports has delivered consistently high levels of reliability, durability, and performance.',
      specifications: {
        'Movement': 'Automatic Calibre 4R36',
        'Case Material': 'Stainless Steel',
        'Case Size': '42.5mm',
        'Glass': 'Hardlex crystal',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '41 Hours',
        'Strap': 'Stainless steel mesh bracelet',
      },
      images: [_sportUrls[0], _classicUrls[2]],
      rating: 4.8,
      reviews: _reviews,
      stock: 18,
      colors: ['Black Dial', 'Blue Pepsi Bezel', 'Orange Dial'],
      sizes: ['42.5mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'seiko-2',
      brand: 'Seiko',
      model: 'Alpinist Prospex',
      category: 'Classic',
      price: 725.00,
      discount: 0.0,
      description: 'Originally designed for Japanese mountain climbers, the modern Prospex Alpinist features an internal rotating compass ring.',
      specifications: {
        'Movement': 'Automatic Calibre 6R35',
        'Case Material': 'Stainless Steel',
        'Case Size': '39.5mm',
        'Glass': 'Sapphire crystal with magnifier lens',
        'Water Resistance': '200m (660 feet)',
        'Power Reserve': '70 Hours',
        'Strap': 'Brown leather strap with deployant clasp',
      },
      images: [_classicUrls[2], _classicUrls[3]],
      rating: 4.7,
      reviews: _reviews,
      stock: 8,
      colors: ['Green Dial', 'Blue Dial', 'Cream Dial'],
      sizes: ['39.5mm'],
      isFeatured: true,
      isPopular: false,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'seiko-3',
      brand: 'Seiko',
      model: 'Presage Cocktail Time',
      category: 'Classic',
      price: 450.00,
      discount: 0.0,
      description: 'Inspired by the glamour of cocktail lounges, the Presage Cockail Time series boasts fine radial pattern pressed dials.',
      specifications: {
        'Movement': 'Automatic Calibre 4R35',
        'Case Material': 'Stainless Steel',
        'Case Size': '40.5mm',
        'Glass': 'Box-shaped Hardlex',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': '41 Hours',
        'Strap': 'Fine leather strap',
      },
      images: [_classicUrls[0], _luxuryUrls[2]],
      rating: 4.9,
      reviews: _reviews,
      stock: 14,
      colors: ['Ice Blue "Skydiving"', 'Espresso', 'Cherry Red'],
      sizes: ['40.5mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'seiko-4',
      brand: 'Seiko',
      model: 'Prospex "Turtle" Diver',
      category: 'Sport',
      price: 495.00,
      discount: 0.10,
      description: 'The Seiko Turtle is an iconic diver\'s watch featuring a comfortable cushion-shaped case resembling a turtle shell.',
      specifications: {
        'Movement': 'Automatic Calibre 4R36',
        'Case Material': 'Stainless Steel',
        'Case Size': '45mm',
        'Glass': 'Hardlex crystal',
        'Water Resistance': '200m (660 feet)',
        'Power Reserve': '41 Hours',
        'Strap': 'Silicone accordion band',
      },
      images: [_sportUrls[2], _sportUrls[0]],
      rating: 4.6,
      reviews: _reviews,
      stock: 12,
      colors: ['Black-Grey', 'Blue wave dial'],
      sizes: ['45mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- CITIZEN (3) ---
    Watch(
      id: 'citizen-1',
      brand: 'Citizen',
      model: 'Eco-Drive Promaster Diver',
      category: 'Sport',
      price: 375.00,
      discount: 0.15,
      description: 'Powered by any light source, this Promaster Diver is an ISO-compliant, reliable diver\'s watch with a durable polyurethane strap.',
      specifications: {
        'Movement': 'Eco-Drive Quartz (Light powered)',
        'Case Material': 'Stainless Steel',
        'Case Size': '44mm',
        'Glass': 'Anti-reflective mineral crystal',
        'Water Resistance': '200m (660 feet)',
        'Power Reserve': 'Eco-Drive (approx. 6 months charge)',
        'Strap': 'Blue polyurethane band',
      },
      images: [_sportUrls[0], _sportUrls[1]],
      rating: 4.7,
      reviews: _reviews,
      stock: 20,
      colors: ['Blue', 'Black'],
      sizes: ['44mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'citizen-2',
      brand: 'Citizen',
      model: 'Tsuyosa Automatic',
      category: 'Classic',
      price: 450.00,
      discount: 0.0,
      description: 'Brings ultra-modern styling straight to your wrist. A beautiful integrated steel sports bracelet watch with vibrant dials.',
      specifications: {
        'Movement': 'Automatic Calibre 8210',
        'Case Material': 'Stainless Steel',
        'Case Size': '40mm',
        'Glass': 'Sapphire crystal with date lens',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': '40 Hours',
        'Strap': 'Integrated presidential steel bracelet',
      },
      images: [_classicUrls[0], _luxuryUrls[2]],
      rating: 4.8,
      reviews: _reviews,
      stock: 22,
      colors: ['Yellow Dial', 'Tiffany Blue Dial', 'Green Dial', 'Black'],
      sizes: ['40mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'citizen-3',
      brand: 'Citizen',
      model: 'Eco-Drive Nighthawk Aviator',
      category: 'Sport',
      price: 395.00,
      discount: 0.10,
      description: 'Designed for pilots, the Nighthawk features a circular slide rule bezel operated by an independent crown at 8 o\'clock.',
      specifications: {
        'Movement': 'Eco-Drive Quartz',
        'Case Material': 'Black Ion-Plated Stainless Steel',
        'Case Size': '42mm',
        'Glass': 'Non-reflective mineral crystal',
        'Water Resistance': '200m (660 feet)',
        'Power Reserve': '180 days power reserve on full light charge',
        'Strap': 'Black steel bracelet',
      },
      images: [_sportUrls[3], _sportUrls[2]],
      rating: 4.6,
      reviews: _reviews,
      stock: 11,
      colors: ['Tactical Black', 'Silver'],
      sizes: ['42mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- TISSOT (3) ---
    Watch(
      id: 'tissot-1',
      brand: 'Tissot',
      model: 'PRX Powermatic 80',
      category: 'Classic',
      price: 650.00,
      discount: 0.05,
      description: 'An essential watch with a retro 1978 design. The integrated case and bracelet, paired with a waffle dial, is an absolute showstopper.',
      specifications: {
        'Movement': 'Automatic Powermatic 80 (80-hour reserve)',
        'Case Material': 'Stainless Steel',
        'Case Size': '40mm',
        'Glass': 'Scratch-resistant sapphire with AR coating',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '80 Hours',
        'Strap': 'Integrated stainless steel bracelet',
      },
      images: [_luxuryUrls[2], _classicUrls[0]],
      rating: 4.9,
      reviews: _reviews,
      stock: 15,
      colors: ['Blue Dial', 'Green Dial', 'Black Dial', 'Ice Blue'],
      sizes: ['35mm', '40mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'tissot-2',
      brand: 'Tissot',
      model: 'Gentleman Powermatic 80',
      category: 'Classic',
      price: 775.00,
      discount: 0.0,
      description: 'The Tissot Gentleman is the perfect multi-purpose watch, both ergonomic and elegant in any circumstance, at home or in business.',
      specifications: {
        'Movement': 'Automatic Powermatic 80 with Silicon hairspring',
        'Case Material': 'Stainless steel with 18k gold bezel',
        'Case Size': '40mm',
        'Glass': 'Domed sapphire crystal',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '80 Hours',
        'Strap': 'Brown alligator-style leather strap',
      },
      images: [_classicUrls[2], _classicUrls[3]],
      rating: 4.7,
      reviews: _reviews,
      stock: 8,
      colors: ['Brown leather', 'Steel blue dial'],
      sizes: ['40mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'tissot-3',
      brand: 'Tissot',
      model: 'Seastar 1000 Chronograph',
      category: 'Sport',
      price: 525.00,
      discount: 0.10,
      description: 'Designed for divers, combining high performance with style. Features unidirectional aluminum dive bezel and sub-second timers.',
      specifications: {
        'Movement': 'Quartz Chronograph G10.212',
        'Case Material': 'Stainless Steel',
        'Case Size': '45.5mm',
        'Glass': 'Scratch-resistant sapphire crystal',
        'Water Resistance': '300m (1,000 feet)',
        'Power Reserve': 'Battery powered',
        'Strap': 'Black rubber strap',
      },
      images: [_sportUrls[2], _sportUrls[0]],
      rating: 4.6,
      reviews: _reviews,
      stock: 14,
      colors: ['Black bezel-Blue Dial', 'Red Bezel'],
      sizes: ['45.5mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- FOSSIL (3) ---
    Watch(
      id: 'fossil-1',
      brand: 'Fossil',
      model: 'Heritage Chronograph',
      category: 'Classic',
      price: 249.00,
      discount: 0.20,
      description: 'Nod to vintage aesthetics. Meticulously built vintage-style watch with stacked chronograph sub-dials and textured dial.',
      specifications: {
        'Movement': 'Quartz Chronograph',
        'Case Material': 'Stainless Steel',
        'Case Size': '43mm',
        'Glass': 'Hardened mineral crystal',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': 'SR621SW Battery',
        'Strap': 'Heritage brown leather strap',
      },
      images: [_classicUrls[2], _classicUrls[1]],
      rating: 4.4,
      reviews: _reviews,
      stock: 30,
      colors: ['Brown Leather', 'Steel Gold Accent'],
      sizes: ['43mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: false,
    ),
    Watch(
      id: 'fossil-2',
      brand: 'Fossil',
      model: 'Townsman Automatic',
      category: 'Classic',
      price: 279.00,
      discount: 0.0,
      description: 'A skeleton dial exposes the intricate inner workings of this industrial-inspired timepiece from townsman series.',
      specifications: {
        'Movement': 'Automatic Mechanical (Self-winding)',
        'Case Material': 'Stainless Steel',
        'Case Size': '44mm',
        'Glass': 'Mineral crystal',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': '40 Hours (approx)',
        'Strap': 'Amber brown leather strap',
      },
      images: [_classicUrls[3], _classicUrls[0]],
      rating: 4.5,
      reviews: _reviews,
      stock: 22,
      colors: ['Brown Leather Skeleton', 'Black Leather Silver case'],
      sizes: ['44mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'fossil-3',
      brand: 'Fossil',
      model: 'Machine Chronograph',
      category: 'Sport',
      price: 189.00,
      discount: 0.15,
      description: 'The industrial details of the Machine watch line make it an instant classic, with knurled bezels and high-durability coatings.',
      specifications: {
        'Movement': 'Quartz Chronograph',
        'Case Material': 'Dark grey ion-plated stainless steel',
        'Case Size': '45mm',
        'Glass': 'Mineral crystal',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': 'Battery powered',
        'Strap': 'Textured silicone and steel hybrid band',
      },
      images: [_sportUrls[3], _sportUrls[1]],
      rating: 4.3,
      reviews: _reviews,
      stock: 40,
      colors: ['Dark Grey', 'Gold-Black'],
      sizes: ['45mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- TITAN (3) ---
    Watch(
      id: 'titan-1',
      brand: 'Titan',
      model: 'Edge Ceramic Ultra-Slim',
      category: 'Classic',
      price: 320.00,
      discount: 0.10,
      description: 'One of the slimmest ceramic watches in the world. Merges advanced design engineering with premium scratch-resistant ceramic build.',
      specifications: {
        'Movement': 'Ultra-slim Quartz (Calibre 1150)',
        'Case Material': 'Ceramic',
        'Case Size': '40mm',
        'Glass': 'Sapphire crystal',
        'Water Resistance': '30m (100 feet)',
        'Power Reserve': 'Battery powered',
        'Strap': 'High-tech ceramic link bracelet',
      },
      images: [_luxuryUrls[3], _classicUrls[1]],
      rating: 4.6,
      reviews: _reviews,
      stock: 12,
      colors: ['Midnight Black', 'Pearl White'],
      sizes: ['40mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'titan-2',
      brand: 'Titan',
      model: 'Regalia Chronograph',
      category: 'Classic',
      price: 240.00,
      discount: 0.0,
      description: 'Perfect for formal dinners and luxury gala events, features multi-dial date-time layout with indices decorated in gold.',
      specifications: {
        'Movement': 'Quartz Chronograph',
        'Case Material': 'Two-Tone Stainless Steel',
        'Case Size': '42mm',
        'Glass': 'Mineral crystal',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': 'Battery powered',
        'Strap': 'Gold and steel link bracelet',
      },
      images: [_luxuryUrls[0], _classicUrls[0]],
      rating: 4.4,
      reviews: _reviews,
      stock: 19,
      colors: ['Gold-Silver Two Tone'],
      sizes: ['42mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: true,
      isRecommended: false,
    ),
    Watch(
      id: 'titan-3',
      brand: 'Titan',
      model: 'Octane Active Sports',
      category: 'Sport',
      price: 195.00,
      discount: 0.08,
      description: 'Sporty timekeeper crafted with tachymeter dial, date display window, and luminous hand dials for dark environments.',
      specifications: {
        'Movement': 'Quartz Calibre Chrono',
        'Case Material': 'Stainless steel with black bezel',
        'Case Size': '44mm',
        'Glass': 'Mineral glass',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': 'Battery',
        'Strap': 'Red accented black silicone strap',
      },
      images: [_sportUrls[1], _sportUrls[2]],
      rating: 4.2,
      reviews: _reviews,
      stock: 26,
      colors: ['Red-Black', 'Blue-Silver'],
      sizes: ['44mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- TAG HEUER (3) ---
    Watch(
      id: 'tag-1',
      brand: 'Tag Heuer',
      model: 'Carrera Chronograph',
      category: 'Luxury',
      price: 6400.00,
      discount: 0.0,
      description: 'Designed as a tribute to the challenging Carrera Panamericana road race. Sporty, elegant chronograph for active men.',
      specifications: {
        'Movement': 'Automatic Heuer 02 Calibre',
        'Case Material': 'Stainless Steel',
        'Case Size': '42mm',
        'Glass': 'Beveled dome sapphire crystal',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '80 Hours',
        'Strap': 'Black alligator leather strap',
      },
      images: [_luxuryUrls[1], _sportUrls[2]],
      rating: 4.8,
      reviews: _reviews,
      stock: 6,
      colors: ['Black Dial', 'Blue Sunray Dial'],
      sizes: ['42mm', '44mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'tag-2',
      brand: 'Tag Heuer',
      model: 'Monaco Calibre 11',
      category: 'Luxury',
      price: 7200.00,
      discount: 0.05,
      description: 'The square-faced legendary watch worn by Steve McQueen. A retro racing classic with left-hand crown layout.',
      specifications: {
        'Movement': 'Automatic Calibre 11',
        'Case Material': 'Stainless Steel (Square)',
        'Case Size': '39mm x 39mm',
        'Glass': 'Sapphire crystal',
        'Water Resistance': '100m (330 feet)',
        'Power Reserve': '40 Hours',
        'Strap': 'Perforated black calfskin racing leather',
      },
      images: [_luxuryUrls[2], _luxuryUrls[3]],
      rating: 4.9,
      reviews: _reviews,
      stock: 4,
      colors: ['Classic McQueen Blue'],
      sizes: ['39mm'],
      isFeatured: true,
      isPopular: false,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'tag-3',
      brand: 'Tag Heuer',
      model: 'Aquaracer Professional 300',
      category: 'Sport',
      price: 3600.00,
      discount: 0.0,
      description: 'A heavy duty luxury tool watch designed for surfing, diving, and deep water sports, featuring a 12-sided ceramic bezel.',
      specifications: {
        'Movement': 'Automatic Calibre 5',
        'Case Material': 'Grade 5 Titanium / Ceramic Bezel',
        'Case Size': '43mm',
        'Glass': 'Sapphire crystal with cyclops eye',
        'Water Resistance': '300m (1,000 feet)',
        'Power Reserve': '38 Hours',
        'Strap': 'Titanium alloy triple-row link bracelet',
      },
      images: [_sportUrls[0], _luxuryUrls[2]],
      rating: 4.7,
      reviews: _reviews,
      stock: 9,
      colors: ['Olive Green Dial', 'Deep Sea Black'],
      sizes: ['43mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- APPLE WATCH (3) ---
    Watch(
      id: 'apple-1',
      brand: 'Apple Watch',
      model: 'Ultra 2',
      category: 'Smartwatch',
      price: 799.00,
      discount: 0.0,
      description: 'The ultimate sports and adventure watch. Featuring a rugged titanium case, up to 72 hours of battery life, and double tap gesture.',
      specifications: {
        'Movement': 'Apple S9 SiP Dual-Core',
        'Case Material': 'Aerospace Grade Titanium',
        'Case Size': '49mm',
        'Glass': 'Flat sapphire crystal front',
        'Water Resistance': '100m (330 feet), Swimproof & recreational dive to 40m',
        'Power Reserve': 'Up to 36 hours (72 hours in low power)',
        'Strap': 'Orange Ocean Band / Trail Loop / Alpine Loop',
      },
      images: [_smartUrls[2], _smartUrls[0]],
      rating: 4.9,
      reviews: _reviews,
      stock: 15,
      colors: ['Titanium Orange', 'Titanium Black', 'Titanium White'],
      sizes: ['49mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'apple-2',
      brand: 'Apple Watch',
      model: 'Series 9',
      category: 'Smartwatch',
      price: 399.00,
      discount: 0.10,
      description: 'A smarter, brighter, and more powerful health companion, with blood oxygen tracking, ECG app, and carbon neutral case options.',
      specifications: {
        'Movement': 'Apple S9 SiP',
        'Case Material': 'Aluminum or Stainless Steel',
        'Case Size': '45mm',
        'Glass': 'Ion-X front glass or Sapphire',
        'Water Resistance': '50m (167 feet) Swimproof',
        'Power Reserve': 'Up to 18 hours (36 in low power)',
        'Strap': 'Midnight sport loop / Milanese loop',
      },
      images: [_smartUrls[0], _smartUrls[1]],
      rating: 4.8,
      reviews: _reviews,
      stock: 25,
      colors: ['Midnight', 'Starlight', 'Silver', 'Graphite'],
      sizes: ['41mm', '45mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'apple-3',
      brand: 'Apple Watch',
      model: 'SE (2nd Gen)',
      category: 'Smartwatch',
      price: 249.00,
      discount: 0.05,
      description: 'Easy ways to stay connected. Active health sensors. Safety features like crash detection. Incredible value watch.',
      specifications: {
        'Movement': 'Apple S8 SiP Dual-Core',
        'Case Material': '100% Recycled Aluminum',
        'Case Size': '44mm',
        'Glass': 'Ion-X glass',
        'Water Resistance': '50m (167 feet)',
        'Power Reserve': 'Up to 18 Hours',
        'Strap': 'Starlight sport band',
      },
      images: [_smartUrls[3], _smartUrls[0]],
      rating: 4.6,
      reviews: _reviews,
      stock: 35,
      colors: ['Starlight SE', 'Midnight SE'],
      sizes: ['40mm', '44mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- SAMSUNG (3) ---
    Watch(
      id: 'samsung-1',
      brand: 'Samsung',
      model: 'Galaxy Watch 6 Classic',
      category: 'Smartwatch',
      price: 399.00,
      discount: 0.12,
      description: 'The return of the physical rotating bezel. Galaxy Watch 6 Classic is a premium smartwatch that offers detailed sleep coach and body stats.',
      specifications: {
        'Movement': 'Exynos W930 (5nm)',
        'Case Material': 'Stainless Steel',
        'Case Size': '47mm',
        'Glass': 'Sapphire Crystal screen',
        'Water Resistance': '50m (167 feet), IP68 & MIL-STD-810H compliant',
        'Power Reserve': 'Up to 40 Hours',
        'Strap': 'Hybrid Eco-Leather band',
      },
      images: [_smartUrls[1], _smartUrls[2]],
      rating: 4.7,
      reviews: _reviews,
      stock: 18,
      colors: ['Black', 'Silver'],
      sizes: ['43mm', '47mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'samsung-2',
      brand: 'Samsung',
      model: 'Galaxy Watch 6 Active',
      category: 'Smartwatch',
      price: 299.00,
      discount: 0.08,
      description: 'Streamlined active lifestyle smartwatch. Thin bezel, lightweight sport casing, with heart rate monitors and automatic workout trackers.',
      specifications: {
        'Movement': 'Exynos W930',
        'Case Material': 'Armor Aluminum',
        'Case Size': '44mm',
        'Glass': 'Sapphire Crystal',
        'Water Resistance': '50m (IP68)',
        'Power Reserve': 'Up to 40 Hours',
        'Strap': 'Sport silicone band',
      },
      images: [_smartUrls[2], _smartUrls[3]],
      rating: 4.6,
      reviews: _reviews,
      stock: 22,
      colors: ['Graphite', 'Silver', 'Gold'],
      sizes: ['40mm', '44mm'],
      isFeatured: false,
      isPopular: true,
      isNewArrival: true,
      isRecommended: true,
    ),
    Watch(
      id: 'samsung-3',
      brand: 'Samsung',
      model: 'Galaxy Watch 5 Pro',
      category: 'Smartwatch',
      price: 449.00,
      discount: 0.15,
      description: 'Outdoor adventurer watch with GPS route tracking, titanium chassis, and largest battery capacity in Galaxy wearable history.',
      specifications: {
        'Movement': 'Exynos W920 (5nm)',
        'Case Material': 'Titanium case',
        'Case Size': '45mm',
        'Glass': 'Sapphire Crystal',
        'Water Resistance': '50m (167 feet) IP68',
        'Power Reserve': 'Up to 80 Hours',
        'Strap': 'D-Buckle sport band',
      },
      images: [_smartUrls[1], _smartUrls[0]],
      rating: 4.5,
      reviews: _reviews,
      stock: 10,
      colors: ['Black Titanium', 'Gray Titanium'],
      sizes: ['45mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),

    // --- HUAWEI (3) ---
    Watch(
      id: 'huawei-1',
      brand: 'Huawei',
      model: 'Watch GT 4 Pro',
      category: 'Smartwatch',
      price: 349.00,
      discount: 0.10,
      description: 'A striking octagonal watch design combining luxury timekeeping aesthetics with 14-day ultra long battery life trackers.',
      specifications: {
        'Movement': 'HarmonyOS proprietary sensor SiP',
        'Case Material': 'Stainless Steel (Octagonal)',
        'Case Size': '46mm',
        'Glass': 'Hardened glass',
        'Water Resistance': '50m (5 ATM)',
        'Power Reserve': 'Up to 14 days',
        'Strap': 'Brown leather strap or steel bracelet',
      },
      images: [_smartUrls[0], _classicUrls[3]],
      rating: 4.7,
      reviews: _reviews,
      stock: 14,
      colors: ['Brown Leather GT', 'Black Steel', 'Green Active'],
      sizes: ['46mm'],
      isFeatured: true,
      isPopular: true,
      isNewArrival: false,
      isRecommended: true,
    ),
    Watch(
      id: 'huawei-2',
      brand: 'Huawei',
      model: 'Watch Ultimate',
      category: 'Smartwatch',
      price: 749.00,
      discount: 0.0,
      description: 'Zirconium-based liquid metal chassis. 100m deep dive safety ratings, and global expedition satellite systems built inside.',
      specifications: {
        'Movement': 'Huawei wearable processor',
        'Case Material': 'Zirconium Liquid Metal / Ceramic Bezel',
        'Case Size': '48.5mm',
        'Glass': 'Thick sapphire crystal',
        'Water Resistance': '100m (10 ATM) ISO 22810 dive compliant',
        'Power Reserve': 'Up to 14 days standard usage',
        'Strap': 'HNBR high durability rubber strap',
      },
      images: [_luxuryUrls[2], _sportUrls[0]],
      rating: 4.8,
      reviews: _reviews,
      stock: 7,
      colors: ['Voyage Blue', 'Expedition Black'],
      sizes: ['48.5mm'],
      isFeatured: true,
      isPopular: false,
      isNewArrival: true,
      isRecommended: false,
    ),
    Watch(
      id: 'huawei-3',
      brand: 'Huawei',
      model: 'Watch Fit 3',
      category: 'Smartwatch',
      price: 139.00,
      discount: 0.0,
      description: 'Ultra-thin, rectangular sleek fitness companion with dynamic training animations, sleep coach and high precision heart sensors.',
      specifications: {
        'Movement': 'Huawei smart sensor processor',
        'Case Material': 'Aluminum Alloy',
        'Case Size': '43.2mm',
        'Glass': 'Corning Gorilla Glass',
        'Water Resistance': '50m (5 ATM)',
        'Power Reserve': 'Up to 10 days',
        'Strap': 'Nylon loop strap or white silicone band',
      },
      images: [_smartUrls[3], _smartUrls[2]],
      rating: 4.5,
      reviews: _reviews,
      stock: 25,
      colors: ['White', 'Black Fit', 'Pink'],
      sizes: ['43.2mm'],
      isFeatured: false,
      isPopular: false,
      isNewArrival: false,
      isRecommended: false,
    ),
  ];
}
